"""initial migration

Revision ID: 3d3a8d995edc
Revises: 
Create Date: 2025-07-21 16:01:33.897851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d3a8d995edc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('diet_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_name', sa.String(length=140), nullable=True),
    sa.Column('portion', sa.Float(), nullable=True),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('meal_type', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diet_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diet_record_timestamp'), ['timestamp'], unique=False)

    op.create_table('exercise_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_type', sa.String(length=140), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('calories_burned', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercise_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercise_record_timestamp'), ['timestamp'], unique=False)

    op.create_table('sleep_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sleep_time', sa.DateTime(), nullable=True),
    sa.Column('wakeup_time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sleep_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sleep_record_sleep_time'), ['sleep_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_sleep_record_wakeup_time'), ['wakeup_time'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sleep_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sleep_record_wakeup_time'))
        batch_op.drop_index(batch_op.f('ix_sleep_record_sleep_time'))

    op.drop_table('sleep_record')
    with op.batch_alter_table('exercise_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercise_record_timestamp'))

    op.drop_table('exercise_record')
    with op.batch_alter_table('diet_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diet_record_timestamp'))

    op.drop_table('diet_record')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
