"""add bmi column to user table

Revision ID: 7ea9b3427d59
Revises: ecbfcedfcce5
Create Date: 2025-07-21 20:55:19.284158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ea9b3427d59'
down_revision = 'ecbfcedfcce5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bmi', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('bmi')

    # ### end Alembic commands ###
