"""refactor exercise goals system

Revision ID: 82bd5cf2dc0b
Revises: 7ea9b3427d59
Create Date: 2025-07-21 21:06:12.480981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82bd5cf2dc0b'
down_revision = '7ea9b3427d59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_goal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal_type', sa.String(length=50), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('exercise_type', sa.String(length=50), nullable=True),
    sa.Column('time_period', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.drop_column('target_exercise_minutes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_exercise_minutes', sa.INTEGER(), nullable=True))

    op.drop_table('exercise_goal')
    # ### end Alembic commands ###
