"""add goal table

Revision ID: ecbfcedfcce5
Revises: 32f954b568e0
Create Date: 2025-07-21 17:56:24.903739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecbfcedfcce5'
down_revision = '32f954b568e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_sleep_hours', sa.Float(), nullable=True),
    sa.Column('target_exercise_minutes', sa.Integer(), nullable=True),
    sa.Column('target_calorie_intake', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goal')
    # ### end Alembic commands ###
